.TH nova\-cells 8
.SH NAME
nova\-cells \- Compute cell communication for Nova

.SH SYNOPSIS
.B nova\-cells
.B \-\-flagfile=<flagfilepath>

.SH DESCRIPTION
.B nova\-cells

This man page is a stub. Please contribute.

.SH PARAMETERS

.LP
.B \-\-flagfile=<flagfilepath>
.IP

Path to the file containing options.
